spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db;MODE=MySQL
    username : sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true